---
kind: Service
apiVersion: v1
metadata:
  name: react-ssr-nginx-service
spec:
  selector:
    app: react-ssr-nginx
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30005
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-ssr-nginx-pdeployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: react-ssr-nginx
    spec:
      containers:
        - name: react-ssr-nginx
          image: vipgit/react-ssr-nginx:1.0.5
          ports:
            - containerPort: 80