version: "3"

services:
  postgres:
    container_name: react-ssr-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - react-advanced-ssr-network
    ports:
      - 5433:5432
  
  frontend:
    container_name: react-ssr-frontend
    hostname: frontend
    depends_on:
      - postgres
      - backend
    build: ./docker/frontend/prod
    networks:
      - react-advanced-ssr-network
    environment:
      - API_URL=http://backend
      - WEB_SOCKET_URL=ws://localhost:8090
    ports: 
      - 8080:80

  backend:
    container_name: react-ssr-backend
    hostname: backend
    depends_on:
      - postgres
    build: ./docker/backend/prod
    networks:
      - react-advanced-ssr-network
    environment:
      - API_DB_HOST=postgres
      - API_DB_PORT=5433
      - API_DB_USERNAME=postgres
      - API_DB_PASSWORD=postgres
      - API_DB_NAME=postgres
    ports: 
      - 8090:80    
      
networks:
  react-advanced-ssr-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24   
    
